"""
Django settings for stockpia project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production production!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-a-default-secret-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
# .env 파일에 DEBUG=true 를 설정하면 디버그 모드가 켜집니다.
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Render 배포 시에는 Render 도메인만 명시하는 것이 좋습니다.
# 로컬 개발 및 WebSocket 테스트를 위해 '*'로 임시 설정합니다.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'channels', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'stocks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # whitenoise 미들웨어 추가
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS 설정: 모든 출처에서의 요청을 허용 (개발 시 편의)
CORS_ALLOW_ALL_ORIGINS = True

# 특정 출처 (프로덕션 환경에서는 CORS_ALLOW_ALL_ORIGINS 대신 사용 권장)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://stockpia-api.onrender.com",
    "http://localhost:5173", # WebSocket 테스트를 위해 추가
]


ROOT_URLCONF = 'stockpia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockpia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise Storage 설정
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ASGI & Channels
ASGI_APPLICATION = 'stockpia.asgi.application'

# Render.com 배포를 위한 Redis URL 환경 변수 사용
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
        },
    },
}

# drf-yasg Swagger UI 설정
if DEBUG:
    # 로컬 개발 환경 설정
    SWAGGER_SETTINGS = {
        'USE_HTTPS_AS_DEFAULT': False, # 로컬에서는 HTTP 사용
        'DEFAULT_API_URL': 'http://127.0.0.1:8000/api/web', # 로컬 개발 서버 URL
    }
else:
    # Render 배포 환경 설정
    SWAGGER_SETTINGS = {
        'USE_HTTPS_AS_DEFAULT': True, # Render에서는 HTTPS 사용
        'DEFAULT_API_URL': 'https://stockpia-api.onrender.com/api/web', # Render 배포 URL
    }

# 공통 설정 (위에서 정의된 SWAGGER_SETTINGS에 추가)
SWAGGER_SETTINGS.update({
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none', # 'none', 'list', 'full'
    'SHOW_REQUEST_HEADERS': True,
    'JSON_EDITOR': True,
    'DEFAULT_MODEL_RENDERING': 'example',
    'DISPLAY_OPERATION_ID': False,
    'DISPLAY_REQUEST_DURATION': True,
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_DEPTH': 3,
})

# Render 배포 환경에서 FORCE_SCRIPT_NAME 경고를 해결하기 위해 추가
FORCE_SCRIPT_NAME = None
