# Generated by Django 6.0.1 on 2026-05-18 13:56

import django.db.models.deletion
import stocks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.CharField(max_length=8)),
                ('password_hash', models.CharField(max_length=128)),
                ('notify_morning', models.BooleanField(default=True)),
                ('notify_evening', models.BooleanField(default=True)),
                ('notify_event', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KisAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.user')),
                ('account_number', models.CharField(max_length=20)),
                ('app_key_enc', models.BinaryField()),
                ('app_secret_key_enc', models.BinaryField()),
                ('env', models.CharField(default='vps', max_length=10)),
                ('permission_scope', models.CharField(default='read_trade', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.user')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkToken',
            fields=[
                ('token', models.CharField(default='96a8af081efa46c986a32f8ce0c21768', max_length=32, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(default=stocks.models.get_token_expiry_date)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', 'sent_at'], name='notif_user_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.user')),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
