# Generated by Django 6.0.1 on 2026-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='default_user', help_text='사용자 식별자', max_length=100, unique=True)),
                ('name', models.CharField(help_text='이름', max_length=50)),
                ('birthdate', models.CharField(help_text='생년월일 (YYYYMMDD)', max_length=8)),
                ('phone', models.CharField(help_text='전화번호', max_length=20)),
                ('account_number', models.CharField(help_text='한국투자증권 계좌번호', max_length=20)),
                ('app_key', models.TextField(help_text='APP_KEY')),
                ('app_secret_key', models.TextField(help_text='APP_SECRET_KEY')),
                ('env', models.CharField(default='vps', help_text='prod(실전) or vps(모의)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
